# Generated by Django 3.2.25 on 2025-02-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
