# Generated by Django 3.2.25 on 2025-02-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250204_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='testimonios/'),
        ),
    ]
