# Generated by Django 3.2.25 on 2025-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250205_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
